export const countryData = [
  {
    code: "DZ",
    iso3: "DZA",
    nameFr: "Algérie",
    nameAr: "الجزائر",
    nameEn: "Algeria",
    currencyCode: "DZD",
    phonePrefix: "+213",
    defaultLocale: "fr",
    isActive: true,
  },
  {
    code: "TN",
    iso3: "TUN",
    nameFr: "Tunisie",
    nameAr: "تونس",
    nameEn: "Tunisia",
    currencyCode: "TND",
    phonePrefix: "+216",
    defaultLocale: "fr",
    isActive: true,
  },
  {
    code: "MA",
    iso3: "MAR",
    nameFr: "Maroc",
    nameAr: "المغرب",
    nameEn: "Morocco",
    currencyCode: "MAD",
    phonePrefix: "+212",
    defaultLocale: "fr",
    isActive: false,
  },
] as const;

export const regionData = [
  { code: 1, countryCode: "DZ", regionType: "wilaya", nameFr: "Adrar", nameAr: "أدرار", nameEn: "Adrar", lat: "27.9767", lng: "-0.2036" },
  { code: 2, countryCode: "DZ", regionType: "wilaya", nameFr: "Chlef", nameAr: "الشلف", nameEn: "Chlef", lat: "36.1647", lng: "1.3315" },
  { code: 3, countryCode: "DZ", regionType: "wilaya", nameFr: "Laghouat", nameAr: "الأغواط", nameEn: "Laghouat", lat: "33.8000", lng: "2.8833" },
  { code: 4, countryCode: "DZ", regionType: "wilaya", nameFr: "Oum El Bouaghi", nameAr: "أم البواقي", nameEn: "Oum El Bouaghi", lat: "35.8775", lng: "7.1136" },
  { code: 5, countryCode: "DZ", regionType: "wilaya", nameFr: "Batna", nameAr: "باتنة", nameEn: "Batna", lat: "35.5559", lng: "6.1744" },
  { code: 6, countryCode: "DZ", regionType: "wilaya", nameFr: "Béjaïa", nameAr: "بجاية", nameEn: "Bejaia", lat: "36.7517", lng: "5.0556" },
  { code: 7, countryCode: "DZ", regionType: "wilaya", nameFr: "Biskra", nameAr: "بسكرة", nameEn: "Biskra", lat: "34.8500", lng: "5.7333" },
  { code: 8, countryCode: "DZ", regionType: "wilaya", nameFr: "Béchar", nameAr: "بشار", nameEn: "Bechar", lat: "31.6167", lng: "-2.2167" },
  { code: 9, countryCode: "DZ", regionType: "wilaya", nameFr: "Blida", nameAr: "البليدة", nameEn: "Blida", lat: "36.4700", lng: "2.8333" },
  { code: 10, countryCode: "DZ", regionType: "wilaya", nameFr: "Bouira", nameAr: "البويرة", nameEn: "Bouira", lat: "36.3800", lng: "3.9000" },
  { code: 11, countryCode: "DZ", regionType: "wilaya", nameFr: "Tamanrasset", nameAr: "تمنراست", nameEn: "Tamanrasset", lat: "22.7850", lng: "5.5228" },
  { code: 12, countryCode: "DZ", regionType: "wilaya", nameFr: "Tébessa", nameAr: "تبسة", nameEn: "Tebessa", lat: "35.4000", lng: "8.1167" },
  { code: 13, countryCode: "DZ", regionType: "wilaya", nameFr: "Tlemcen", nameAr: "تلمسان", nameEn: "Tlemcen", lat: "34.8783", lng: "-1.3150" },
  { code: 14, countryCode: "DZ", regionType: "wilaya", nameFr: "Tiaret", nameAr: "تيارت", nameEn: "Tiaret", lat: "35.3667", lng: "1.3167" },
  { code: 15, countryCode: "DZ", regionType: "wilaya", nameFr: "Tizi Ouzou", nameAr: "تيزي وزو", nameEn: "Tizi Ouzou", lat: "36.7167", lng: "4.0500" },
  { code: 16, countryCode: "DZ", regionType: "wilaya", nameFr: "Alger", nameAr: "الجزائر", nameEn: "Algiers", lat: "36.7538", lng: "3.0588" },
  { code: 17, countryCode: "DZ", regionType: "wilaya", nameFr: "Djelfa", nameAr: "الجلفة", nameEn: "Djelfa", lat: "34.6667", lng: "3.2500" },
  { code: 18, countryCode: "DZ", regionType: "wilaya", nameFr: "Jijel", nameAr: "جيجل", nameEn: "Jijel", lat: "36.8167", lng: "5.7667" },
  { code: 19, countryCode: "DZ", regionType: "wilaya", nameFr: "Sétif", nameAr: "سطيف", nameEn: "Setif", lat: "36.1917", lng: "5.4139" },
  { code: 20, countryCode: "DZ", regionType: "wilaya", nameFr: "Saïda", nameAr: "سعيدة", nameEn: "Saida", lat: "34.8333", lng: "0.1500" },
  { code: 21, countryCode: "DZ", regionType: "wilaya", nameFr: "Skikda", nameAr: "سكيكدة", nameEn: "Skikda", lat: "36.8667", lng: "6.9000" },
  { code: 22, countryCode: "DZ", regionType: "wilaya", nameFr: "Sidi Bel Abbès", nameAr: "سيدي بلعباس", nameEn: "Sidi Bel Abbes", lat: "35.2000", lng: "-0.6333" },
  { code: 23, countryCode: "DZ", regionType: "wilaya", nameFr: "Annaba", nameAr: "عنابة", nameEn: "Annaba", lat: "36.9000", lng: "7.7667" },
  { code: 24, countryCode: "DZ", regionType: "wilaya", nameFr: "Guelma", nameAr: "قالمة", nameEn: "Guelma", lat: "36.4667", lng: "7.4333" },
  { code: 25, countryCode: "DZ", regionType: "wilaya", nameFr: "Constantine", nameAr: "قسنطينة", nameEn: "Constantine", lat: "36.3650", lng: "6.6147" },
  { code: 26, countryCode: "DZ", regionType: "wilaya", nameFr: "Médéa", nameAr: "المدية", nameEn: "Medea", lat: "36.2667", lng: "2.7500" },
  { code: 27, countryCode: "DZ", regionType: "wilaya", nameFr: "Mostaganem", nameAr: "مستغانم", nameEn: "Mostaganem", lat: "35.9333", lng: "0.0833" },
  { code: 28, countryCode: "DZ", regionType: "wilaya", nameFr: "M'Sila", nameAr: "المسيلة", nameEn: "MSila", lat: "35.7000", lng: "4.5333" },
  { code: 29, countryCode: "DZ", regionType: "wilaya", nameFr: "Mascara", nameAr: "معسكر", nameEn: "Mascara", lat: "35.4000", lng: "0.2000" },
  { code: 30, countryCode: "DZ", regionType: "wilaya", nameFr: "Ouargla", nameAr: "ورقلة", nameEn: "Ouargla", lat: "31.9500", lng: "5.3167" },
  { code: 31, countryCode: "DZ", regionType: "wilaya", nameFr: "Oran", nameAr: "وهران", nameEn: "Oran", lat: "35.6971", lng: "-0.6308" },
  { code: 32, countryCode: "DZ", regionType: "wilaya", nameFr: "El Bayadh", nameAr: "البيض", nameEn: "El Bayadh", lat: "33.6833", lng: "1.0167" },
  { code: 33, countryCode: "DZ", regionType: "wilaya", nameFr: "Illizi", nameAr: "إليزي", nameEn: "Illizi", lat: "26.4833", lng: "8.4667" },
  { code: 34, countryCode: "DZ", regionType: "wilaya", nameFr: "Bordj Bou Arréridj", nameAr: "برج بوعريريج", nameEn: "Bordj Bou Arreridj", lat: "36.0667", lng: "4.7667" },
  { code: 35, countryCode: "DZ", regionType: "wilaya", nameFr: "Boumerdès", nameAr: "بومرداس", nameEn: "Boumerdes", lat: "36.7667", lng: "3.4772" },
  { code: 36, countryCode: "DZ", regionType: "wilaya", nameFr: "El Tarf", nameAr: "الطارف", nameEn: "El Tarf", lat: "36.7672", lng: "8.3138" },
  { code: 37, countryCode: "DZ", regionType: "wilaya", nameFr: "Tindouf", nameAr: "تندوف", nameEn: "Tindouf", lat: "27.6753", lng: "-8.1286" },
  { code: 38, countryCode: "DZ", regionType: "wilaya", nameFr: "Tissemsilt", nameAr: "تيسمسيلت", nameEn: "Tissemsilt", lat: "35.6000", lng: "1.8167" },
  { code: 39, countryCode: "DZ", regionType: "wilaya", nameFr: "El Oued", nameAr: "الوادي", nameEn: "El Oued", lat: "33.3500", lng: "6.8500" },
  { code: 40, countryCode: "DZ", regionType: "wilaya", nameFr: "Khenchela", nameAr: "خنشلة", nameEn: "Khenchela", lat: "35.4333", lng: "7.1433" },
  { code: 41, countryCode: "DZ", regionType: "wilaya", nameFr: "Souk Ahras", nameAr: "سوق أهراس", nameEn: "Souk Ahras", lat: "36.2833", lng: "7.9500" },
  { code: 42, countryCode: "DZ", regionType: "wilaya", nameFr: "Tipaza", nameAr: "تيبازة", nameEn: "Tipaza", lat: "36.5833", lng: "2.4500" },
  { code: 43, countryCode: "DZ", regionType: "wilaya", nameFr: "Mila", nameAr: "ميلة", nameEn: "Mila", lat: "36.4500", lng: "6.2500" },
  { code: 44, countryCode: "DZ", regionType: "wilaya", nameFr: "Aïn Defla", nameAr: "عين الدفلى", nameEn: "Ain Defla", lat: "36.2667", lng: "1.9667" },
  { code: 45, countryCode: "DZ", regionType: "wilaya", nameFr: "Naâma", nameAr: "النعامة", nameEn: "Naama", lat: "33.2667", lng: "-0.3167" },
  { code: 46, countryCode: "DZ", regionType: "wilaya", nameFr: "Aïn Témouchent", nameAr: "عين تموشنت", nameEn: "Ain Temouchent", lat: "35.3000", lng: "-1.1333" },
  { code: 47, countryCode: "DZ", regionType: "wilaya", nameFr: "Ghardaïa", nameAr: "غرداية", nameEn: "Ghardaia", lat: "32.4833", lng: "3.6667" },
  { code: 48, countryCode: "DZ", regionType: "wilaya", nameFr: "Relizane", nameAr: "غليزان", nameEn: "Relizane", lat: "35.7333", lng: "0.5500" },
  { code: 49, countryCode: "DZ", regionType: "wilaya", nameFr: "Timimoun", nameAr: "تيميمون", nameEn: "Timimoun", lat: "29.2583", lng: "0.2306" },
  { code: 50, countryCode: "DZ", regionType: "wilaya", nameFr: "Bordj Badji Mokhtar", nameAr: "برج باجي مختار", nameEn: "Bordj Badji Mokhtar", lat: "21.3333", lng: "0.9500" },
  { code: 51, countryCode: "DZ", regionType: "wilaya", nameFr: "Ouled Djellal", nameAr: "أولاد جلال", nameEn: "Ouled Djellal", lat: "34.4333", lng: "5.0667" },
  { code: 52, countryCode: "DZ", regionType: "wilaya", nameFr: "Béni Abbès", nameAr: "بني عباس", nameEn: "Beni Abbes", lat: "30.1333", lng: "-2.1667" },
  { code: 53, countryCode: "DZ", regionType: "wilaya", nameFr: "In Salah", nameAr: "عين صالح", nameEn: "In Salah", lat: "27.2000", lng: "2.4833" },
  { code: 54, countryCode: "DZ", regionType: "wilaya", nameFr: "In Guezzam", nameAr: "عين قزام", nameEn: "In Guezzam", lat: "19.6500", lng: "5.7667" },
  { code: 55, countryCode: "DZ", regionType: "wilaya", nameFr: "Touggourt", nameAr: "تقرت", nameEn: "Touggourt", lat: "33.1000", lng: "6.0667" },
  { code: 56, countryCode: "DZ", regionType: "wilaya", nameFr: "Djanet", nameAr: "جانت", nameEn: "Djanet", lat: "24.5500", lng: "9.4833" },
  { code: 57, countryCode: "DZ", regionType: "wilaya", nameFr: "El M'Ghair", nameAr: "المغير", nameEn: "El M'Ghair", lat: "33.9500", lng: "5.9167" },
  { code: 58, countryCode: "DZ", regionType: "wilaya", nameFr: "El Meniaa", nameAr: "المنيعة", nameEn: "El Meniaa", lat: "30.5833", lng: "2.8833" },
  { code: 101, countryCode: "TN", regionType: "governorate", nameFr: "Tunis", nameAr: "تونس", nameEn: "Tunis", lat: "36.8065", lng: "10.1815" },
  { code: 102, countryCode: "TN", regionType: "governorate", nameFr: "Ariana", nameAr: "أريانة", nameEn: "Ariana", lat: "36.8625", lng: "10.1956" },
  { code: 103, countryCode: "TN", regionType: "governorate", nameFr: "Ben Arous", nameAr: "بن عروس", nameEn: "Ben Arous", lat: "36.7531", lng: "10.2189" },
  { code: 104, countryCode: "TN", regionType: "governorate", nameFr: "Manouba", nameAr: "منوبة", nameEn: "Manouba", lat: "36.8101", lng: "10.0956" },
  { code: 105, countryCode: "TN", regionType: "governorate", nameFr: "Nabeul", nameAr: "نابل", nameEn: "Nabeul", lat: "36.4513", lng: "10.7350" },
  { code: 106, countryCode: "TN", regionType: "governorate", nameFr: "Zaghouan", nameAr: "زغوان", nameEn: "Zaghouan", lat: "36.4029", lng: "10.1429" },
  { code: 107, countryCode: "TN", regionType: "governorate", nameFr: "Bizerte", nameAr: "بنزرت", nameEn: "Bizerte", lat: "37.2744", lng: "9.8739" },
  { code: 108, countryCode: "TN", regionType: "governorate", nameFr: "Béja", nameAr: "باجة", nameEn: "Beja", lat: "36.7256", lng: "9.1817" },
  { code: 109, countryCode: "TN", regionType: "governorate", nameFr: "Jendouba", nameAr: "جندوبة", nameEn: "Jendouba", lat: "36.5011", lng: "8.7802" },
  { code: 110, countryCode: "TN", regionType: "governorate", nameFr: "Kef", nameAr: "الكاف", nameEn: "Kef", lat: "36.1822", lng: "8.7148" },
  { code: 111, countryCode: "TN", regionType: "governorate", nameFr: "Siliana", nameAr: "سليانة", nameEn: "Siliana", lat: "36.0840", lng: "9.3708" },
  { code: 112, countryCode: "TN", regionType: "governorate", nameFr: "Sousse", nameAr: "سوسة", nameEn: "Sousse", lat: "35.8256", lng: "10.6369" },
  { code: 113, countryCode: "TN", regionType: "governorate", nameFr: "Monastir", nameAr: "المنستير", nameEn: "Monastir", lat: "35.7643", lng: "10.8113" },
  { code: 114, countryCode: "TN", regionType: "governorate", nameFr: "Mahdia", nameAr: "المهدية", nameEn: "Mahdia", lat: "35.5047", lng: "11.0622" },
  { code: 115, countryCode: "TN", regionType: "governorate", nameFr: "Sfax", nameAr: "صفاقس", nameEn: "Sfax", lat: "34.7406", lng: "10.7603" },
  { code: 116, countryCode: "TN", regionType: "governorate", nameFr: "Kairouan", nameAr: "القيروان", nameEn: "Kairouan", lat: "35.6781", lng: "10.0963" },
  { code: 117, countryCode: "TN", regionType: "governorate", nameFr: "Kasserine", nameAr: "القصرين", nameEn: "Kasserine", lat: "35.1676", lng: "8.8365" },
  { code: 118, countryCode: "TN", regionType: "governorate", nameFr: "Sidi Bouzid", nameAr: "سيدي بوزيد", nameEn: "Sidi Bouzid", lat: "35.0382", lng: "9.4858" },
  { code: 119, countryCode: "TN", regionType: "governorate", nameFr: "Gabès", nameAr: "قابس", nameEn: "Gabes", lat: "33.8815", lng: "10.0982" },
  { code: 120, countryCode: "TN", regionType: "governorate", nameFr: "Médenine", nameAr: "مدنين", nameEn: "Medenine", lat: "33.3549", lng: "10.5055" },
  { code: 121, countryCode: "TN", regionType: "governorate", nameFr: "Tataouine", nameAr: "تطاوين", nameEn: "Tataouine", lat: "32.9297", lng: "10.4518" },
  { code: 122, countryCode: "TN", regionType: "governorate", nameFr: "Gafsa", nameAr: "قفصة", nameEn: "Gafsa", lat: "34.4250", lng: "8.7842" },
  { code: 123, countryCode: "TN", regionType: "governorate", nameFr: "Tozeur", nameAr: "توزر", nameEn: "Tozeur", lat: "33.9197", lng: "8.1335" },
  { code: 124, countryCode: "TN", regionType: "governorate", nameFr: "Kébili", nameAr: "قبلي", nameEn: "Kebili", lat: "33.7050", lng: "8.9650" },
] as const;
